#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
编译期脚本：从 data/dictionary/*.txt 中提取所有 1 对多字的映射，
生成 C++ 头文件，编译进 DLL，供 RegionalReplacer.py 通过 ctypes 读取。
"""

import os
import sys


def build_multi_char_dict(dict_dir: str) -> dict:
    """对齐 Lexicon::ParseKeyValues 的解析逻辑"""
    result = {}
    if not os.path.isdir(dict_dir):
        print(f"警告: 字典目录不存在: {dict_dir}")
        return result

    for filename in sorted(os.listdir(dict_dir)):
        if not filename.endswith('.txt'):
            continue

        filepath = os.path.join(dict_dir, filename)
        dict_name = filename[:-4]
        temp_map = {}

        with open(filepath, 'r', encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith('#'):
                    continue

                tab_pos = line.find('\t')
                if tab_pos == -1:
                    continue
                key = line[:tab_pos]
                values_str = line[tab_pos + 1:]

                values = values_str.split(' ')
                values = [v for v in values if v]

                if key not in temp_map:
                    temp_map[key] = []
                for v in values:
                    if v not in temp_map[key]:
                        temp_map[key].append(v)

        char_map = {k: v for k, v in temp_map.items() if len(v) >= 2}
        result[dict_name] = char_map

        if char_map:
            print(f"  {filename}: {len(char_map)} 个多字映射")
        else:
            print(f"  {filename}: (无多字映射)")

    return result


def main():
    if len(sys.argv) != 3:
        print("用法: build_multi_char_dict.py <字典目录> <输出头文件路径>")
        sys.exit(1)

    dict_dir = sys.argv[1]
    output_path = sys.argv[2]

    print("正在提取一字对多字映射...")
    multi_char_dict = build_multi_char_dict(dict_dir)

    total = sum(len(v) for v in multi_char_dict.values())
    print(f"共提取 {total} 个多字映射，分布在 {len(multi_char_dict)} 个字典文件中")

    config_to_char = {
        's2t':      'STCharacters',
        's2tw':     'STCharacters',
        's2twp':    'STCharacters',
        's2hk':     'STCharacters',
        's2hkp':    'STCharacters',
        't2s':      'TSCharacters',
        'tw2s':     'TSCharacters',
        'tw2sp':    'TSCharacters',
        'hk2s':     'TSCharacters',
        'hk2sp':    'TSCharacters',
        't2tw':     'TWVariants',
        'tw2t':     'TWVariantsRev',
        't2hk':     'HKVariants',
        'hk2t':     'HKVariantsRev',
        't2jp':     'JPShinjitaiCharacters',
        'jp2t':     'JPShinjitaiCharactersRev',
        's2t_jieba':     'STCharacters',
        's2tw_jieba':    'STCharacters',
        's2twp_jieba':   'STCharacters',
        's2hk_jieba':    'STCharacters',
        's2hkp_jieba':   'STCharacters',
        'hk2sp_jieba':   'TSCharacters',
        'tw2sp_jieba':   'TSCharacters',
    }

    with open(output_path, 'w', encoding='utf-8', newline='\n') as f:
        f.write('// Auto-generated by build_multi_char_dict.py. DO NOT EDIT.\n')
        f.write('#pragma once\n')
        f.write('#include <string>\n')
        f.write('#include <unordered_map>\n\n')

        f.write('static const std::unordered_map<std::string, std::string> kConfigToCharDict = {\n')
        for k, v in sorted(config_to_char.items()):
            f.write(f'    {{"{k}", "{v}"}},\n')
        f.write('};\n\n')

        f.write('static const std::unordered_map<std::string, std::unordered_map<std::string, std::string>> kMultiCharDict = {\n')
        for dict_name in sorted(multi_char_dict.keys()):
            f.write(f'    {{"{dict_name}", {{\n')
            for key in sorted(multi_char_dict[dict_name].keys()):
                value = ' '.join(multi_char_dict[dict_name][key])
                f.write(f'        {{"{key}", "{value}"}},\n')
            f.write('    }},\n')
        f.write('};\n')

    print(f"已生成: {output_path}")


if __name__ == '__main__':
    main()