#!/usr/bin/env python3
"""
ZIP 资源生成器，用于生成 opencc_data.zip 资源包或内嵌到 DLL 中。

Usage:
    python3 pack_assets.py pack <data_dir> <output_zip>
    python3 pack_assets.py embed <zip_file> <output_header>

pack  - 扫描目录，以最大压缩率打包为 ZIP
embed - 读取 ZIP 文件，转成 C 数组头文件
"""

import sys
import zipfile
from pathlib import Path


def cmd_pack():
    data_dir = Path(sys.argv[2])
    output = Path(sys.argv[3])
    with zipfile.ZipFile(output, 'w', zipfile.ZIP_DEFLATED, compresslevel=9) as zf:
        for f in sorted(data_dir.rglob('*')):
            if f.is_file():
                arcname = str(f.relative_to(data_dir)).replace('\\', '/')
                zf.write(f, arcname)
    print(f"Packed {output} ({output.stat().st_size} bytes)")


def cmd_embed():
    zip_path = Path(sys.argv[2])
    output = Path(sys.argv[3])
    with open(zip_path, 'rb') as f:
        zip_bytes = f.read()
    with open(output, 'w', encoding='utf-8', newline='\n') as f:
        f.write('// Auto-generated by pack_assets.py. DO NOT EDIT.\n')
        f.write('#pragma once\n')
        f.write('#include <cstddef>\n\n')
        f.write('#define OPENCC_EMBEDDED_ASSETS_AVAILABLE\n\n')
        f.write('namespace opencc::embedded {\n\n')
        f.write(f'static const size_t kEmbeddedZipSize = {len(zip_bytes)};\n')
        f.write('static const unsigned char kEmbeddedZip[] = {\n')
        for i in range(0, len(zip_bytes), 16):
            chunk = zip_bytes[i:i+16]
            f.write('    ' + ', '.join(f'0x{b:02x}' for b in chunk) + ',\n')
        f.write('};\n\n')
        f.write('} // namespace opencc::embedded\n')
    print(f"Generated {output} ({len(zip_bytes)} bytes)")


def main():
    if len(sys.argv) < 2:
        print("Usage: python3 pack_assets.py pack <data_dir> <output_zip>")
        print("       python3 pack_assets.py embed <zip_file> <output_header>")
        sys.exit(1)
    if sys.argv[1] == 'pack':
        cmd_pack()
    elif sys.argv[1] == 'embed':
        cmd_embed()
    else:
        print(f"Unknown command: {sys.argv[1]}")
        sys.exit(1)


if __name__ == '__main__':
    main()